'use strict';
const {chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{const root=path.resolve(__dirname,'../..');const server=http.createServer((req,res)=>{let file=path.resolve(root,'.'+new URL(req.url,'http://local').pathname);if(!file.startsWith(root+path.sep))return res.writeHead(403).end();if(fs.existsSync(file)&&fs.statSync(file).isDirectory())file=path.join(file,'index.html');if(!fs.existsSync(file))return res.writeHead(404).end();res.setHeader('Content-Type',{'.js':'text/javascript','.css':'text/css','.html':'text/html'}[path.extname(file)]||'text/plain');fs.createReadStream(file).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:3,isMobile:true,hasTouch:true});const errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(new URL(r.url()).hostname!=='127.0.0.1')external.push(r.url());});await page.goto(`http://127.0.0.1:${server.address().port}/works/morning-thread-02/`);await page.waitForTimeout(1000);console.log('BOOT',errors,await page.evaluate(()=>({sse:!!window.SSE,app:window.SSE?.app.current(),work:!!window.MorningThread02,diag:window.SSE?.diagnostics.summary()})));await page.screenshot({path:'/tmp/morning02-boot.png'});await page.waitForFunction(()=>window.MorningThread02&&window.SSE?.app.current()==='morning',{},{timeout:3000});const client=await page.context().newCDPSession(page);
const coord=async p=>page.evaluate(p=>{const v=SSE.viewport;return {x:v.offsetX+p.x*v.scale,y:innerHeight-v.offsetY-p.y*v.scale};},p);
const snap=()=>page.evaluate(()=>MorningThread02.snapshot());
const tap=async p=>{const q=await coord(p);await page.touchscreen.tap(q.x,q.y);await page.waitForTimeout(50);};
const positions={start:{x:195,y:515},coffee:{x:95,y:430},laundry:{x:288,y:415},bag:{x:120,y:260},door:{x:283,y:210}};
async function trace(ids,cancel=false){const first=await coord(positions[ids[0]]);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...first,id:1}]});let prev=first;for(const id of ids.slice(1)){const next=await coord(positions[id]);for(let i=1;i<=15;i++){await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:prev.x+(next.x-prev.x)*i/15,y:prev.y+(next.y-prev.y)*i/15,id:1}]});await page.waitForTimeout(6);}prev=next;}await client.send('Input.dispatchTouchEvent',{type:cancel?'touchCancel':'touchEnd',touchPoints:[]});await page.waitForTimeout(80);}
await trace(['start','coffee','bag','coffee','start']);assert.deepEqual((await snap()).route,[]);
await trace(['start','coffee','bag','laundry','door']);assert.deepEqual((await snap()).route,['coffee','bag','laundry','door']);await page.screenshot({path:'/tmp/morning02-plan.png'});
await tap({x:283,y:107});await page.waitForFunction(()=>MorningThread02.snapshot().mode==='change');assert.deepEqual((await snap()).done,['coffee']);assert.equal((await snap()).clock,491);await page.screenshot({path:'/tmp/morning02-change.png'});await tap({x:283,y:107});await trace(['coffee','bag','laundry','door']);await tap({x:283,y:107});await page.waitForFunction(()=>MorningThread02.snapshot().mode==='success');assert.equal((await snap()).clock,499);await page.screenshot({path:'/tmp/morning02-success.png'});
await tap({x:195,y:107});assert.equal((await snap()).clock,488);await trace(['start','coffee','laundry','bag','door']);await tap({x:283,y:107});await page.waitForFunction(()=>MorningThread02.snapshot().mode==='change');await tap({x:283,y:107});await trace(['coffee','laundry','bag','door']);await tap({x:283,y:107});await page.waitForFunction(()=>MorningThread02.snapshot().mode==='failure');assert.equal((await snap()).clock,502);
await tap({x:40,y:50});await trace(['start','coffee'],true);assert.deepEqual((await snap()).route,['coffee']);await tap(positions.bag);assert.deepEqual((await snap()).route,['coffee','bag']);await tap({x:40,y:50});
for(const size of [{width:375,height:667},{width:430,height:932},{width:844,height:390}]){await page.setViewportSize(size);await page.waitForTimeout(180);await trace(['start','bag']);assert.deepEqual((await snap()).route,['bag']);await tap({x:40,y:50});console.log('LAYOUT',size,await page.evaluate(()=>({scroll:document.documentElement.scrollHeight,h:innerHeight,w:innerWidth,body:document.body.scrollHeight})));assert.equal(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight&&scrollY===0),true);}
await page.setViewportSize({width:390,height:844});await tap({x:342,y:50});await trace(['start','coffee']);await page.waitForTimeout(1200);const report=await page.evaluate(()=>SSE.dev.report());fs.writeFileSync('/tmp/morning02-diagnostics.json',JSON.stringify(report,null,2));assert.equal(report.app.engineVersion,'0.3.0');assert.equal(report.diagnostics.summary.error,0);assert.deepEqual(errors,[]);assert.deepEqual(external,[]);const quality=await page.evaluate(()=>({width:gameCanvas.width,height:gameCanvas.height,dpr:devicePixelRatio}));assert.equal(quality.width,1170);console.log(JSON.stringify({result:'PASS',quality,errors,external,diagnostics:report.diagnostics,performance:report.performance},null,2));
}finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
